### PR TITLE
Fixed font-family: mono to font-family: monospace

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
Aside: I'm having fun playing with this, but the use of symbolset makes it frustrating to use. When updating the sass, I couldn't compile it to css since I don't have symbolset.

**Comment by ianstormtaylor** [comment]
Hey @StevenClontz glad you're digging it. Good call on the Symbolset, I should only ignore the font files themselves instead of the entire directory, so that the style file is included.

I'd rather not completely change all the fonts and everything though, so I'm gonna close this and make the `monospace` change manually.

**Comment by StevenClontz** [comment]
Sounds good - the rest of the commits changing the fonts were for my own fork since the fonts this project uses aren't free. It's my first pull request so I didn't know the later commits would be made part of the request - I figured you'd just want to fix the mono -> monospace typo. 

That allows for the correct fall-back on the monospace and serif fonts. It'd be nice to have a better fall-back for the icon fonts for those of us who don't want to pay for symbolset, however; right now the buttons are just blank (which is way I edited mine to use the font-awesome CDN). Thanks again!

**Comment by ianstormtaylor** [comment]
Ah, yup. When you pull request it always references the most recent commit of the branch you pull requested. Normally, you'd want to create a branch on your fork named something like `monospace-fix` and then pull-request from that branch instead of `master`. That way you can keep doing whatever you want on your `master` and it won't be included. 

Just pushed the `monospace` fix live!

**Comment by StevenClontz** [comment]
Okay, cool! It looks like you've hotlinked to socrates.io's hosted version of Symbolset - is the licensing okay to use those for my forked project? I definitely prefer the look of those icons over the FontAwesome icons I patched in myself.

The Adobe fonts you've used for the monospace and serif typefaces are 403-ing for me when I run the project either locally or on my github page: http://stevenclontz.github.com/socrates/ Those will fall back to whatever the browser uses for monospace or serif naturally (once I update my github page with the fixed typo), so it's not too much trouble, although I'll probably specifically define other fonts for my own project.

**Comment by ianstormtaylor** [comment]
Yeah that makes sense, Typekit only works on white-listed domains. So if you want custom fonts in your fork you'll need to figure out your own solution for that.

No idea what the licensing means for Symbolset, my guess is you should buy your own copy if you want to use them.

**Pull request closed without merging**
